const brinquedos = [
  {
    id: 1,
    nome: "Woody",
    tipo: "Boneco",
    anoFabricacao: 1950,
    cor: "Marrom",
    quantidadeEstoque: 15,
  },
  {
    id: 2,
    nome: "Buzz Lightyear",
    tipo: "Robô",
    anoFabricacao: 1995,
    cor: "Branco e Verde",
    quantidadeEstoque: 20,
  },
  {
    id: 3,
    nome: "Jessie",
    tipo: "Boneca",
    anoFabricacao: 1955,
    cor: "Vermelho e Branco",
    quantidadeEstoque: 10,
  },
  {
    id: 4,
    nome: "Senhor Cabeça de Batata",
    tipo: "Brinquedo",
    anoFabricacao: 1952,
    cor: "Marrom",
    quantidadeEstoque: 8,
  },
  {
    id: 5,
    nome: "Rex",
    tipo: "Dinossauro",
    anoFabricacao: 1990,
    cor: "Verde",
    quantidadeEstoque: 5,
  },
  {
    id: 6,
    nome: "Slinky",
    tipo: "Cachorro de Mola",
    anoFabricacao: 1950,
    cor: "Marrom",
    quantidadeEstoque: 12,
  },
  {
    id: 7,
    nome: "Bo Peep",
    tipo: "Boneca de Porcelana",
    anoFabricacao: 1955,
    cor: "Rosa e Branco",
    quantidadeEstoque: 7,
  },
  {
    id: 8,
    nome: "Soldados Verdes",
    tipo: "Soldados de Plástico",
    anoFabricacao: 1960,
    cor: "Verde",
    quantidadeEstoque: 30,
  },
  {
    id: 9,
    nome: "Aliens (Pequenos)",
    tipo: "Alien",
    anoFabricacao: 1995,
    cor: "Verde Claro",
    quantidadeEstoque: 25,
  },
  {
    id: 10,
    nome: "Bala no Alvo",
    tipo: "Cavalo de Brinquedo",
    anoFabricacao: 1955,
    cor: "Marrom",
    quantidadeEstoque: 9,
  },
];

export default { brinquedos };
